### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by apyxpi** [dipeira/proteas#20]
Το αρχεία του project είναι σε κωδικοποίηση ISO-8859-7. Υπάρχει περίπτωση να γίνουν διαθέσιμα σε utf-8 ?

**Comment by Sugarv** [comment]
Η μετατροπή άρχισε στο branch utf8 και θα ενσωματωθεί σύντομα, μετά από το σχετικό testing!

**Comment by Sugarv** [comment]
Έκλεισε με το d4eaac9
